version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: AdvisorApp/Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: advisor-app/Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
